71/dance

commands/generate.ts
Hey,
I could not compile your extension using 
```
vsce package
```
because
```
yarn run generate
```
already failed with
```
$ ts-node commands/generate.ts && ts-node package.ts                                                                                                                        
/home/geier/misc/dance/node_modules/ts-node/src/index.ts:245
return new TSError(diagnosticText, diagnosticCodes)
^
TSError: ⨯ Unable to compile TypeScript:
package.ts:3:10 - error TS2724: Module '"./commands"' has no exported member 'commands'. Did you mean 'ICommand'?
3 import { commands } from './commands'
```
It turned out that `commands/index.ts` and `README.md` has not been generated completely.
Problem was that only the first `write(...)` was written because the `close()` at the end of the …
=> Fixed stream close() to end()

src/utils/prompt.ts
Hi,
just trying to check this extension out and couldn't use the goto commands because they simply wouldn't do anything. 
I know nothing about VS Code extensions, but it seems `selectedItems` was `length:0`, so I peaked into quickPick and saw that activeItems had the choosen command inside. 
Maybe that helps...
=> 'fix' goto throwing null exception

package.json, package.ts, src/commands/changes.ts, src/commands/index.ts, src/commands/move.ts, src/extension.ts
This defaults to true (existing behavior). When set to false, all selections keep at least one character.
Fixes #44.
Note that even with this change, the selection is not fully Kak/Vim-like. In kak, one-character selections have the same anchor and cursor and thus can be extended to either side, where as in VSCode one-character selections can be either forward or backwards, and will respond differently to expansions in Dance. Fixing that will require a much larger PR.
=> Add dance.selections.allowEmpty configuration.

src/commands/selectObject.ts
Close #55 
It should correct many boundary issues.
=> correct character index for findObjectWithChars

src/commands/index.ts
Closes #61 
When the range of the selection was larger than the viewport, the revealRange command did scroll to the top of the selection, hiding the cursor. This pull request improves this behavior by making sure that the cursor is always visible.
=> correct scrolling when selection range > visible range

src/commands/move.ts
Simplify scroll commands and make them compatible with "editor.scrollBeyondLastLine". The `Command.upPage` function did not work when the visible range was just one line.
=> correct scroll commands

commands/README.md, commands/commands.yaml, commands/index.ts, package.json, src/commands/multiple.ts
In kakoune, when using select on a block of text, the last occurence of the selected string is set set as the main selection. This pull request also change the rotate commands to be coherent with the change.
=> correct selection order to be more kakoune-like

package.json, package.ts, src/state/extension.ts
It turns out VSCode already merges user-specified menu objects with the Dance default menu objects. From [API documentation](https://github.com/yuchenshi/dance/pull/new/merge-menu):
> The effective value (returned by get) is computed by overriding or merging the values in the following order.
> **Note: Only object value types are merged and all other value types are overridden.**
I've improved the error handling logic to show the exact key definitions in conflict, which should help users troubleshoot conflicts more easily.
For example, in the case of:
```json
"object": {
"items": {
"b": { "command": "xxx", "text": "xxx" },
},
}
```
This now shows that there is a conflict between `b()` (from default) and `b` (from user settings). I've also made it possible to work around this situation by …
=> Improve menu items merging.

src/api/run.ts
I ran into the issue that if I insert the result of a shell command (using `!`), I get the result as a JSON object.
So I execute the following command: `#echo test`
And I get the following output:
```
{"val":"test"}
```
This PR returns the result of executing a command as a string. So it would return "test" instead.
I don't know why the previous version returned the result as a JSON object, i.e. which usecase it is for. But this solution fits my usecase.
=> Return result of shell as string

README.md
Hi
I recently asked myself "How many status bar segments are provided by Dance?". After a small visit in the code, I think it would be a nice addition to have the answer available directly in the readme.
Thanks
=> doc: add section about status bar segments

src/api/selections.ts
Does the same as VSCodeVim https://github.com/VSCodeVim/Vim/blob/6d76ea60d3ce97a20cc3c22ebf58a2d61e7705db/src/mode/modeHandler.ts#L1648
=> enable word highlighting for dance selection

src/commands/README.md, src/commands/edit.ts, src/commands/layouts/azerty.fr.md, src/commands/layouts/qwerty.md, src/commands/load-all.ts, test/suite/commands/edit-align.md, test/suite/commands/edit-align.test.ts
I added support for aligning over multiple columns, mimicking the behavior of kakoune when having more than one selection per line.
=> Align over multiple columns

meta.ts
Keybindings are currently limited to 2 per command because `replace` only replaces the first match when the 1st arg is a string. This seems unintentional.
`replaceAll` is not available in the ES version targeted, but we can use a regexp as the 1st argument to replace all occurrences.
This is useful when tinkering with the code to add new keybindings, [such as those from Helix "select" mode](https://github.com/71/dance/issues/299).
=> fix: allow more than 2 keybindings per command

meta.ts, package.build.ts, package.json, src/api/data/commands.yaml, src/commands/README.md, src/commands/edit.ts, src/commands/history.ts, src/commands/layouts/azerty.fr.md, src/commands/layouts/qwerty.md, src/commands/load-all.ts, src/commands/modes.ts, src/commands/seek.ts, src/commands/select.ts
Related to https://github.com/71/dance/issues/299
This adds [helix select mode](https://docs.helix-editor.com/keymap.html#select--extend-mode) inspired keybindings.
The just reuse existing commands and are defined as `helix: select` as opposed to existing other modes such as `kakoune: normal` etc. As far as I know, the `kakoune` or `helix` part of the string is not used yet, but this could be useful in the future.
By default, no keybinding is assigned to enter the new select mode from normal mode. Users need to assign one themselves (I assigned `v` to mine as Helix does, which is already used in dance/kakoune). Or they can just enter it via the VSCode command selection.
Available commands in this mode are `esc` (return to normal mode), `u s+u` undo/redo (same as normal mode), the …
=> feat: add Helix-based select mode and its most common keybindings

src/commands/seek.ts
clear unrelated unlabeledSelection highlight after 2ndChar was pressed.
When I type s to start an leap action, and type `a` as the 1st input:
<image width=200
src="https://github.com/71/dance/assets/30321432/d444c8e3-a89b-4419-a797-8671522124c2"/>
Then, I wanna choose the position with prefix-"aj", so I type `j`.
<p>
<image width=200 alt="Before this PR"
src="https://github.com/71/dance/assets/30321432/2e9a3de8-1e4c-4421-89bd-1d5c340f3f38"/>
<image width=200 alt="After this PR"
src="https://github.com/71/dance/assets/30321432/4579bd7d-15ae-4817-a808-7fbc4982aabc"/>
</p>
Left: Before this PR; Right: After this PR.
As the pic shows, before this PR, there are some unrelated highlight remained, such as `"ab" "an" "as"`.
=> leap command highlighting rule improved.

package.build.ts, package.json, src/api/menu.ts, src/commands/edit.ts, yarn.lock
Heya, thanks for maintaining this.
When playing with Strackeror's great Helix mode contribution, I was having trouble getting a command-hx menu to feel right due to the single hot key system. E.g. distilled to a three item menu, "fmt / Format", "w / Write", and "wbc / Write and Close", `w` and `wbc` can't be distinguished in the current system.
As a proof of concept, I wondered if menus could have a `menu_type: "hotkey"` (current behaviour, and default) or alternatively a `menu_type: "palette"`, which is just a stock-standard vscode quickpick. Palette menus don't have the hotkey system but can just use vscode's already great type/select system which I've been using locally quite happily.
Demo:
https://github.com/user-attachments/assets/5729f88b-8efd-4492-a3a9-9f5532bff41c …
=> Allow ordinary menus

extensions/helix/package.build.ts, extensions/helix/package.json, src/api/data/commands.yaml, src/commands/README.md, src/commands/layouts/azerty.fr.md, src/commands/layouts/qwerty.md, src/commands/seek.ts
This pull request adds `ms`, `mr`, and `md` to the Helix keymap, along with the following fixes:
* Line numbers are now absolute in `helix/insert` and `helix/select`, relative in `helix/normal`.
* Unimpaired mappings `[` and `]` are added back to the Helix keymap, they were missing for some reason.
All these keybinds use existing Dance commands, the only limitation being that `md` will replace the nearest pair instead of asking for the pair to delete. It may be more efficient to implement these as commands, though I understand that the core is still supposed to be Kakoune-based.
=> feat: Add the rest of match mode to Helix keymap

extensions/helix/package.build.ts, extensions/helix/package.json
Generating a pre-release which looks like 0.1.0001 broke VS Code:
> ScanningExtension: Cannot read the extension from
> $HOME/.vscode/extensions/gregoire.dance-helix-0.1.0001
=> misc: bump Helix version to 0.1.1

src/commands/README.md, src/commands/layouts/azerty.fr.md, src/commands/layouts/qwerty.md, src/commands/search.ts
The "smart select" logic considered that a newline was a word boundary, and inserted a `\b`, which doesn't actually match a newline.
Also replace newlines with `\n` to make sure the prompt doesn't erase newlines.
Fixes #390.
=> .search.selection: do not add `\b` after line end

extensions/helix/package.build.ts, extensions/helix/package.json, meta.ts, src/api/data/commands.yaml, src/commands/README.md, src/commands/layouts/azerty.fr.md, src/commands/layouts/qwerty.md, src/commands/misc.ts
Add 'Goto next paragraph' and 'Goto previous paragraph' to helix, under the keybinds `[p` and `]p`.
=> Add paragraph to helix bracket menus
